### ISSUE TITLE
Indexing large files

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [ENCODE-DCC/encoded#2220]
Hi,

How would you index large files ( >1GB) for region search?

Thank you very much!
Parul

**Comment by hitz** [comment]
I think it's like 4GB.  But probably should just break up the payload into smaller objects and submit them serially?

**Comment by Parul-Kudtarkar** [comment]
@hitz Is there a script to break the payload and serial submission, or probably we have to write one?

**Comment by hitz** [comment]
no script for that...  is it the region_indexer.py code that crashes?  Hmm.. that's the new name.  peak_indexer.py maybe?    What is the actual stacktrace and how do you trigger it?

**Comment by Parul-Kudtarkar** [comment]
Usually I do not see any errors logged(with log statements) by peak_indexer.py script in apache logs. Probably since the indexing limit is exceeded the file is never indexed by ES. Let me look into this more and get back to you. @hitz thanks a lot!

**Comment by Parul-Kudtarkar** [comment]
The only error I see in the logs and that is completely unrelated to indexing big files but slowing down indexing in general -

WARNING [encoded.peak_indexer][listener] {'xmin': 323165, 'types': None, 'indexed': 96699, 'errors': ["KeyError('/files/TSTFF345228_deleted/@@object',)"], 'last_xmin': None}
INFO [snovault.elasticsearch.es_index_listener][listener] {'stats': {'rss_change': 224014336, 'es_count': 2, 'rss_begin': 964112384, 'wsgi_begin': 1526365188845229, 'wsgi_time': 33997953, 'wsgi_end': 1526365222843182, 'es_time': 4920, 'db_time': 3605864, 'rss_end': 1188126720, 'db_count': 3745}, 'types': None, 'timestamp': '2018-05-15T06:20:22.872059', 'errors': ["KeyError('/files/TSTFF345228_deleted/@@object',)"], 'last_xmin': None, 'xmin': 323165, 'indexed': 96699}
{'xmin': 323165, 'types': None, 'indexed': 96699, 'errors': ["KeyError('/files/TSTFF345228_deleted/@@object',)"], 'last_xmin': None}

It is not a good idea to bypass  HTTPNotFound exception in embed.py 
Any thoughts on how to fix this?

**Comment by hitz** [comment]
Hmm... it seems like you want to remove the link/reverse link/embedding that is pointing to TSTFF345228_deleted.

But I doubt that has much of a performance impact.

**Comment by tdreszer** [comment]
Two issues as far as indexing large files by region_indexer (aka file or peak_indexer)...

1) Current code downloads the file into memory before doing any indexing.  From the in memory file it creates an in memory set of locations by chrom and only then talks to elasticsearch. This is the most probable source of the problem.  New code (in a branch) can avoid part of this by writing a temp local file then reading that line by line.  Without this, 60M SNPs could not be indexed.

2) The contents of a single "document" indexed to es contains all the locations per chrom for one file.  Since each chrom is a separate index, the memory burden _could_ be broken up by file.  However, this can only be done if the file is in chrom sort order.  There is code in that separate branch that can do this, however it only does this for our SNP set, since that is known to be in chrom order.

Unfortunately, it would take a larger redesign than currently anticipated to break the 1 doc per whole chrom per file burden.  So if _THAT_ gets to violating elasticsearch limits we will be in trouble.  However, I am willing to be that the change in (1) above will solve the problems currently being experienced.

**Comment by Parul-Kudtarkar** [comment]
@tdreszer thanks!
We will implement latest changes to indexer and hopefully ES indexing of in (temp) local file instead of  in memory should resolve the issue! If not we will at our end implement similar function to the code for indexing large SNP files that you had mentioned. We will keep you posted.

**Comment by Parul-Kudtarkar** [comment]
I think till the time we mention in the peak indexer script what field we want to index your approach should work. Sorry this is a naive question but could you please clarify - "but the whole file isn't read into memory at one time" 
Is it read per chromosome or read as chucks of certain size?

**Comment by tdreszer** [comment]
could you please clarify - "but the whole file isn't read into memory at one time"
In current production code, the whole remote file is read into memory and _then_ gzip opened and read from memory line by line.  In the code on our branch, large remote files are copied locally and gzip.open'd to read them line by line.

**Comment by hitz** [comment]
Also - @tdreszer clarified something for me - each chromosome in each BED *is* indexed as a single document.  So a very large number of lines in a BED on a specific chromosome could go over ES 4GB limit.    Probably would have to modify region-search somewhat do do it a different way... or you could break them up into smaller objects, would probably still work (as long as uuid field in mapping isn't unique)
